### PR TITLE
Add href argument to `create` function

### PR DESCRIPTION
**Pull request by Shastel**

### CODE REVIEW

**Comment by JudahGabriel** [comment]
@Shastel Can you explain what this does? What purpose is the href argument?

**Comment by Shastel** [comment]
Hi @JudahGabriel 
I believe that it has nothing to do inside of the `create` function yet but it seems that general API for the `create` function was updated and without this change, I wasn't able to run the builder locally.

Please see `pwabuilder-windows10` as an API reference
https://github.com/pwa-builder/pwabuilder-windows10/blob/c6347b0dcbed362ddeecbfe36b968b7e7b5b409f/lib/platform.js#L50

**Comment by Shastel** [comment]
Also, I believe that [this commit](https://github.com/pwa-builder/pwabuilder-windows10/commit/77b81e1682038f3a9b1878aeeeef5a002b3718c3) did exactly the same

**Comment by JudahGabriel** [comment]
Thanks. Closing, as it's already in the code.

**Pull request closed without merging**
